### ISSUE TITLE
Make Featured-article and article page working

### ISSUE THREAD

**Issue by SV9045** [ajitsinghkaler/devto-clone#1]
#### as data is emitted already about all articles, let's make Featured-article Page working. Data will be passed to featured-article component and then Open it via URL, Considering Mobile First Approach.

**Comment by ajitsinghkaler** [comment]
I'm working on that next Thursday I've already done the CSS Can you pick something else

**Comment by ajitsinghkaler** [comment]
Try to pick something completely different from what I'm working on. Like details page
