### ISSUE TITLE
Add Listings Page

### ISSUE THREAD

**Issue by ChellappanRajan** [ajitsinghkaler/devto-clone#10]
Hi @ajitsinghkaler  Currently Listings page is not implemented. Can we add Listings page?

**Comment by ajitsinghkaler** [comment]
Can you write the details here how you implemented it

**Comment by ajitsinghkaler** [comment]
Go for it. I just want to know how will you manage different heights in listing cards

**Comment by ChellappanRajan** [comment]
Hi @ajitsinghkaler After doing lot of research I found that we can use grid masonry layout for listing cards

**Comment by ajitsinghkaler** [comment]
Go for it

**Comment by ajitsinghkaler** [comment]
Comment here how you implement it

**Comment by ChellappanRajan** [comment]
Sure wil add more details once I started working on that part.

**Comment by ajitsinghkaler** [comment]
Thanks

**Comment by ChellappanRajan** [comment]
> Thanks

#16 Here is Issue for tracking remaining functioanlity.

**Comment by ajitsinghkaler** [comment]
I'll review everything tomorrow.
