### ISSUE TITLE
Add precommit hooks

### ISSUE THREAD

**Issue by ajitsinghkaler** [ajitsinghkaler/devto-clone#8]
We want to add precommit hooks so that of linting or tests(which will be added later on) if fails then commit cannot happen

**Comment by sardapv** [comment]
You might want to restructure using my https://github.com/sardapv/angular-material-starter-template which would add most of your tools so you can focus on main app😀✌️.

**Comment by ajitsinghkaler** [comment]
It has just too much stuff Jest, Cypress, Tailwind, Material ui I don't want to add all that rn

**Comment by ajitsinghkaler** [comment]
Fixed by #24
